# Generated by Django 2.2 on 2022-04-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite seu Nome', max_length=150)),
                ('email', models.EmailField(help_text='Digite seu Email', max_length=254)),
                ('assunto', models.CharField(help_text='Digite o Assunto', max_length=150)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Newletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Digite seu Email', max_length=254)),
            ],
        ),
    ]
