# Generated by Django 2.2 on 2022-04-01 19:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titulo do Capítulo', max_length=150)),
                ('subtitle', models.CharField(help_text='Subtitulo do capítulo', max_length=150)),
                ('status', models.CharField(choices=[('vigente', 'Vigente'), ('revogado', 'revogado')], default='vigente', help_text='Status do código no momento atual', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('slug', models.SlugField(help_text='Slug é um campo em modo de preenchimento automático, mas se você quiser, pode modificar seu conteúdo', unique='True', verbose_name='Slug')),
                ('status', models.CharField(choices=[('1', 'No prazo'), ('2', 'Atrasado'), ('3', 'Concluído')], default=1, max_length=7)),
                ('descricao', models.TextField()),
                ('data_entrega', models.DateTimeField(blank=True, help_text='Estipular data para entrega dos documentos da gestão anterior', null=True)),
                ('data_entregou', models.DateTimeField(blank=True, help_text='Data que foi entregue os documentos da gestão anterior', null=True)),
                ('complete_per', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Regimento_Interno',
            fields=[
                ('id', models.CharField(help_text='numero do código', max_length=150, primary_key=True, serialize=False)),
                ('codigo', models.TextField(help_text='código')),
                ('status', models.CharField(choices=[('vigente', 'Vigente'), ('revogado', 'revogado')], default='vigente', help_text='Status do código no momento atual', max_length=150)),
                ('title', models.ManyToManyField(to='administration.Capitulo')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('slug', models.SlugField(help_text='Slug é um campo em modo de preenchimento automático, mas se você quiser, pode modificar seu conteúdo')),
                ('descricao', models.CharField(max_length=100)),
                ('data_entrega', models.DateTimeField(blank=True, help_text='Estipular data para entrega dos documentos da gestão anterior', null=True)),
                ('data_entregou', models.DateTimeField(blank=True, help_text='Data que foi entregue os documentos da gestão anterior', null=True)),
                ('status', models.CharField(choices=[(0, 'ABERTA'), (1, 'TRABALHANDO'), (2, 'PAUSADA'), (3, 'CONCLUíDA')], default=0, max_length=19)),
                ('complete_per', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('documentos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='administration.Checklist')),
            ],
            options={
                'db_table': 'tarefa',
            },
        ),
    ]
