# Generated by Django 2.2 on 2022-04-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('pago', 'Pago'), ('atrasado', 'Atrasado'), ('inadimplente', 'Inadimplete'), ('acordo', 'Acordo')], default='aberto', max_length=28)),
                ('unidade', models.CharField(help_text='Unidade docondomínio', max_length=150)),
                ('codigo_banco', models.CharField(default='104', help_text='Código do Banco', max_length=5, verbose_name='Código do Banco')),
                ('carteira', models.CharField(max_length=5)),
                ('aceite', models.CharField(default='N', max_length=1)),
                ('valor_documento', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor do Documento')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_documento', models.DateField(verbose_name='Data do Documento')),
                ('data_processamento', models.DateField(auto_now=True, verbose_name='Data de Processamento')),
                ('numero_documento', models.CharField(max_length=11, verbose_name='Número do Documento')),
                ('agencia_cedente', models.CharField(max_length=4, verbose_name='Agência Cedente')),
                ('conta_cedente', models.CharField(max_length=7, verbose_name='Conta Cedente')),
                ('cedente', models.CharField(max_length=255, verbose_name='Nome do Cedente')),
                ('cedente_documento', models.CharField(max_length=50, verbose_name='Documento do Cedente')),
                ('cedente_cidade', models.CharField(max_length=255, verbose_name='Cidade do Cedente')),
                ('cedente_uf', models.CharField(max_length=2, verbose_name='Estado do Cedente')),
                ('cedente_endereco', models.CharField(max_length=255, verbose_name='Endereço do Cedente')),
                ('cedente_bairro', models.CharField(max_length=255, verbose_name='Bairro do Cedente')),
                ('cedente_cep', models.CharField(max_length=9, verbose_name='CEP do Cedente')),
                ('sacado_nome', models.CharField(max_length=255, verbose_name='Sacado')),
                ('sacado_documento', models.CharField(max_length=255, verbose_name='Documento do Sacado')),
                ('sacado_cidade', models.CharField(max_length=255, verbose_name='Cidade do Sacado')),
                ('sacado_uf', models.CharField(max_length=2, verbose_name='Estado do Sacado')),
                ('sacado_endereco', models.CharField(max_length=255, verbose_name='Endereço do Sacado')),
                ('sacado_bairro', models.CharField(max_length=255, verbose_name='Bairro do Sacado')),
                ('sacado_cep', models.CharField(max_length=9, verbose_name='CEP do Sacado')),
                ('quantidade', models.CharField(blank=True, max_length=10, verbose_name='Quantidade')),
                ('especie_documento', models.CharField(blank=True, max_length=255, verbose_name='Espécie do Documento')),
                ('especie', models.CharField(default='R$', max_length=2, verbose_name='Espécie')),
                ('moeda', models.CharField(default='9', max_length=2)),
                ('local_pagamento', models.CharField(default='Pagável em qualquer banco até o vencimento', max_length=255, verbose_name='Local de Pagamento')),
                ('demonstrativo', models.TextField(blank=True)),
                ('instrucoes', models.TextField(default='1- Não receber após 20 dias.\n2- Multa de 2,00% =R$ 1,30 após o vencimento.\n3- Taxa diária de permanência de 0,033% a.d.= R$ 0,02/dia ')),
            ],
        ),
    ]
