# Generated by Django 2.2 on 2022-04-01 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('moradores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertencia',
            fields=[
                ('id', models.CharField(help_text='Indentificador id da Advertência', max_length=150, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('analizando', 'Analizando'), ('concluido', 'Concluido')], default='analizando', max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Data da criação da Advertência')),
                ('unidade', models.CharField(help_text='Unidade do morador', max_length=9)),
                ('termo_proibido', models.CharField(help_text='definição do termo proibido', max_length=400)),
                ('data_reclamacao', models.DateTimeField(auto_now_add=True, help_text='Data Relamação por morador')),
                ('fato_ocorrido', models.TextField(help_text='descrição do fato ocorrido')),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morador_advertencia', to='moradores.Morador')),
                ('regimento_interno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_advertencia', to='administration.Regimento_Interno')),
                ('sindico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sindico_atual_advertencia', to='accounts.Administradores')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.URLField(blank=True, help_text=' logo da categoria', null=True)),
                ('title', models.CharField(help_text='O titulo da categoria prestação de serviço', max_length=150)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Condominios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('start_of_activities', models.DateTimeField(blank=True, verbose_name='Início das atividades')),
                ('main_activity', models.CharField(blank=True, default='Condomínios Prediais', max_length=150)),
                ('descritpion', models.TextField(blank=True, verbose_name='Descricao do condominio')),
                ('logo', models.ImageField(help_text='logotipo do condominio', upload_to='settings/img')),
                ('img', models.URLField(help_text='Image do Condominio')),
                ('google_analytics', models.TextField(blank=True, verbose_name='Google Analytics Code')),
                ('cnpj', models.CharField(blank=True, max_length=150)),
                ('inscricao_estatual', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('address', models.CharField(blank=True, max_length=190, verbose_name='Endereço')),
                ('cep', models.CharField(blank=True, max_length=150, verbose_name='CEP da Localidade')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Estado')),
                ('status', models.CharField(choices=[('Positivo', 'Positivo'), ('negativo', 'Negativo'), ('inadimplente', 'Inadimplente')], default='Positivo', max_length=100)),
                ('uf', models.CharField(default='DF', help_text='O UF do estador exemplo DF', max_length=2)),
                ('city', models.CharField(blank=True, max_length=190, verbose_name='Cidade')),
                ('phone', phone_field.models.PhoneField(blank=True, default='(00) 0000-0000', help_text='Numero do Telefone', max_length=31)),
                ('periodo', models.DateTimeField(help_text='Periodo do movimento')),
                ('is_active', models.BooleanField(blank=True, default=False, verbose_name='Está ativo?')),
                ('receitas', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Total das Receitas Condominial', max_digits=10)),
                ('despesas', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Total das Despesas Condominial', max_digits=10)),
                ('inadinplencia', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Total do valor dos Inadinplentes', max_digits=10)),
                ('caixa', models.DecimalField(decimal_places=2, default=0, help_text='Caixa do condomino', max_digits=10)),
                ('valor_taxa', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Valor da taxa mensal', max_digits=10)),
                ('taxa_extra_ordinaria', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Valor da taxa Ordinária', max_digits=10)),
                ('fundo_de_reserva', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Valor da taxa Ordinária', max_digits=10)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Valor total da taxa mensal', max_digits=10)),
                ('lancamento_futuro', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Boletos a serem pagos', max_digits=10)),
                ('conta_corrente', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Saldo da Conta Corrente', max_digits=10)),
                ('conta_poupança', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Saldo da Poupança', max_digits=10)),
                ('administradores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrador_condominio', to='accounts.Administradores')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuário_administrador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Condomínio',
                'verbose_name_plural': 'Condomínio',
            },
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.CharField(help_text='Indentificador id da multa', max_length=150, primary_key=True, serialize=False)),
                ('data_aplicacao', models.DateTimeField(auto_now_add=True, help_text='Data da aplicação da Multa')),
                ('valor_multa', models.DecimalField(decimal_places=2, default=0, help_text='valor total da multa', max_digits=10)),
                ('data_decorrente', models.CharField(help_text='Data das advertências', max_length=150)),
                ('prazo', models.DateTimeField(help_text='Data de termino do prazo')),
                ('local_data', models.CharField(help_text='Ex. Brasilia 01 de Janeiro de 2021', max_length=280)),
                ('Advertencia', models.ManyToManyField(help_text='Advertência Aplicadas', to='condominio.Advertencia')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condominio_multa', to='condominio.Condominios')),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morador_multa', to='moradores.Morador')),
                ('sindico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sindico_atual_multa', to='accounts.Administradores')),
            ],
        ),
        migrations.CreateModel(
            name='Taxa_Ordinaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text=' Criação da Taxa Condominal Mensal')),
                ('updated', models.DateTimeField(auto_now_add=True, help_text='Taxa Condominal Mensal')),
                ('taxa', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Taxa Ordinária Condiminial Mensal', max_digits=10)),
                ('extra', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Taxa Extraordinária Condiminial Mensal', max_digits=10)),
                ('fundo', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Taxa para Fundo de Reserva', max_digits=10)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Total das Taxas mensais', max_digits=10)),
                ('multa_mes', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Porcetagem do valor da multa mensal', max_digits=10)),
                ('multa_diaria', models.CharField(blank=True, help_text='Porcetagem do valor da multa diaria', max_length=11)),
                ('administradores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to='accounts.Administradores')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxa_odinaria', to='condominio.Condominios')),
            ],
            options={
                'verbose_name': 'Taxa Ordinaria',
                'verbose_name_plural': 'Taxas Ordinaria',
            },
        ),
        migrations.CreateModel(
            name='Taxa_Extraordinaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text=' Criação da Taxa Condominal Extraordinária')),
                ('updated', models.DateTimeField(auto_now_add=True, help_text='Taxa Condominal Extraordinária')),
                ('inicio', models.DateTimeField(help_text=' Inicio da Taxa CondominalExtraordinária')),
                ('fim', models.DateTimeField(help_text='Fim da Taxa Condominal Extraordinária')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Valor das Taxas Extraordinária', max_digits=10)),
                ('administradores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administradora_extraordinaria', to='accounts.Administradores')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxa_extraordinaria', to='condominio.Condominios')),
            ],
            options={
                'verbose_name': 'Taxa Extraordinária',
                'verbose_name_plural': 'Taxas Extraordinária',
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='O titulo da categoria prestação de serviço', max_length=150)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='condominio.Categoria')),
            ],
            options={
                'verbose_name': 'Sub-Categoria',
                'verbose_name_plural': 'Sub Categorias',
            },
        ),
        migrations.CreateModel(
            name='Recurso_Multa',
            fields=[
                ('id', models.CharField(help_text='Indentificador id da multa', max_length=150, primary_key=True, serialize=False)),
                ('data_recurso', models.DateTimeField(auto_now_add=True, help_text='Data criação do recurso')),
                ('apelacao', models.TextField(help_text='argumento da apelação')),
                ('local_data', models.CharField(help_text='Ex. Brasilia 01 de Janeiro de 2021', max_length=280)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condominio_recurso', to='condominio.Condominios')),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morador_recurso', to='moradores.Morador')),
                ('multa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informativo_recurso', to='condominio.Multa')),
                ('sindico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sindico_multa_recurso', to='accounts.Administradores')),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencias',
            fields=[
                ('id', models.CharField(help_text='Indentificador id da Ocorrência', max_length=150, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('analizando', 'Analizando'), ('concluido', 'Concluido')], default='analizando', max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Data da criação da ocorrência')),
                ('data_da_ocorrencia', models.DateTimeField(help_text='Data da criação da ocorrência')),
                ('unidade', models.CharField(help_text='Unidade do autor da ocorrência', max_length=150)),
                ('declarante', models.CharField(help_text='Pessoas que esta fazendo a ocorrência', max_length=150)),
                ('unidade_envolvida', models.CharField(help_text='unidade envolvida na ocorrência', max_length=150)),
                ('declarado', models.CharField(help_text='Pessoas que esta fazendo a ocorrência', max_length=150)),
                ('descricao', models.TextField(help_text='Descrição da Ocorrêcia')),
                ('dias', models.IntegerField(help_text='Dias Restante')),
                ('sindico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sindico_atual_ocorrencia', to='accounts.Administradores')),
            ],
        ),
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.CharField(help_text='Numero do Contrato', max_length=150, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('aluguel', 'Aluguel'), ('seguro', 'Seguro'), ('manutenção', 'Manutenção')], default='aluguel', max_length=150)),
                ('status', models.CharField(choices=[('vigente', 'Vigente'), ('não vigente', 'Não Vigente')], default='vigente', max_length=150)),
                ('img', models.ImageField(upload_to='logo/empresa/contrato')),
                ('empresa', models.CharField(help_text='Nome da Empresa', max_length=150)),
                ('descricao', models.TextField(help_text='Descrição')),
                ('inicio', models.DateTimeField(help_text='Data de Inicio do Contrato')),
                ('termino', models.DateTimeField(help_text='Termino do Contrato')),
                ('parcelas', models.IntegerField(help_text='A quantidade de parcelas')),
                ('valor_parcelas', models.DecimalField(decimal_places=2, help_text=' Valor da Parcelas', max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, help_text='Valor total do Contratos', max_digits=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_categoria', to='condominio.Categoria')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategoria_contrato', to='condominio.SubCategoria')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='Arrecadacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='O dia que gerado o relatório')),
                ('data_referencia', models.DateTimeField(help_text='Data de Referência')),
                ('arrecadacao_prevista', models.DecimalField(decimal_places=2, help_text=' Arrecadação Prevista', max_digits=10)),
                ('arrecadacao_realizada', models.DecimalField(decimal_places=2, help_text=' Arrecadação Realizada', max_digits=10)),
                ('Gastos', models.DecimalField(decimal_places=2, help_text='Gasto Mensal', max_digits=10)),
                ('inadimplencia', models.DecimalField(decimal_places=2, help_text='Total da Inadimplência', max_digits=10)),
                ('saldo_geral', models.DecimalField(decimal_places=2, help_text='Saldo Geral', max_digits=10)),
                ('administradores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrador_atual', to='accounts.Administradores')),
                ('condominios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analise_mensal', to='condominio.Condominios')),
            ],
        ),
    ]
