# Generated by Django 2.2 on 2022-04-01 19:01

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(help_text='Unidade', max_length=150)),
                ('img', models.ImageField(blank=True, upload_to='User')),
                ('proprietario', models.CharField(blank=150, max_length=150)),
                ('emergencia', models.CharField(blank=150, max_length=150)),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(blank=True, max_length=150, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=150, verbose_name='RG')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail')),
                ('endereco', models.CharField(blank=True, max_length=190, verbose_name='Endereço')),
                ('date_of_birth', models.DateTimeField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('quantidade', models.IntegerField(blank=True, default='0', help_text='Quantidade de moradores fixo')),
                ('estado', models.CharField(blank=True, max_length=100, verbose_name='Estado')),
                ('financeiro', models.CharField(blank=True, choices=[('em dia', 'Em dia'), ('atrasada', 'Atrasada'), ('inadinplente', 'Inadinplente'), ('paga', 'Paga')], default='em dia', max_length=28)),
                ('status', models.CharField(blank=True, choices=[('proprietario', 'Proprietario'), ('iquilino', 'Inquilino')], default='proprietario', max_length=100, verbose_name='Satus')),
                ('uf', models.CharField(blank=True, help_text='UF do estado', max_length=150)),
                ('genero', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], default='masculino', max_length=100, verbose_name='Genero')),
                ('city', models.CharField(blank=True, max_length=190, verbose_name='Cidade')),
                ('bairro', models.CharField(blank=True, help_text='bairro do Morador', max_length=150)),
                ('cep', models.CharField(blank=True, help_text='Cep da rua do  Morador', max_length=150)),
                ('telefone', phone_field.models.PhoneField(blank=True, help_text='Telefone para contato', max_length=31)),
                ('is_active', models.BooleanField(blank=True, default=False, verbose_name='Está ativo?')),
                ('carro', models.BooleanField(blank=True, help_text='O morador tem Carro', verbose_name='Tem Veiculo')),
                ('animais', models.BooleanField(blank=True, help_text='Posssuidor de animais de Pequeno Porte', verbose_name='Tem Animais')),
                ('taxa', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Taxa Condominial', max_digits=10, null=True)),
                ('taxa_extra', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Taxa Exraordinaria', max_digits=10, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Valor Total', max_digits=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data do cadastramento do Morador')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Data da ultima atualização dos dados do morador')),
                ('mudanca', models.DateTimeField(blank=True, help_text='Data que Morador mudou', null=True)),
                ('saida', models.DateTimeField(blank=True, help_text='Data do Morador saiu', null=True)),
                ('entrada', models.DateTimeField(blank=True, null=True, verbose_name='Data de Entrada')),
                ('funcionario', models.BooleanField(blank=True, default=False, help_text='O morador tem funcionario')),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administradores', to='accounts.Administradores')),
            ],
            options={
                'verbose_name': 'Modador',
                'verbose_name_plural': 'Moradores',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.CharField(help_text='Numero da garagem', max_length=40, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto')], default='carro', help_text='O tipo do Veiculo do Morador', max_length=150)),
                ('status', models.CharField(choices=[('autorizado', 'Autorizado'), ('não autorizado', 'Não Autorizado'), ('avaliação', 'Avaliação')], default='avaliação', help_text='Status do Veiculo', max_length=150)),
                ('condicao', models.CharField(choices=[('proprietario', 'Proprietário'), ('aluguel', 'Aluguel')], default='proprietario', help_text='Condição da Vaga de Garagem', max_length=150)),
                ('marca', models.CharField(blank=True, help_text='A Marca do Veiculo', max_length=150)),
                ('modelo', models.CharField(blank=True, help_text='A Modelo do Veiculo', max_length=150)),
                ('cor', models.CharField(blank=True, help_text='A Cor da Pintura do Veiculo', max_length=150)),
                ('placa', models.CharField(blank=True, help_text='A placa do Veiculo', max_length=150)),
                ('img', models.ImageField(blank=True, help_text='Image do veiculo do Morador', upload_to='Veiculo/Morador')),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condutor', to='moradores.Morador')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parente', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('responsável', 'Responsável'), ('esposo', 'Esposo'), ('esposa', 'Esposa'), ('pai', 'PAi'), ('mãe', 'Mãe'), ('filho', 'Filho'), ('filha', 'Filha'), ('irmão', 'Irmão'), ('irmã', 'Irmã'), ('tio', 'Tio'), ('tia', 'Tia'), ('sobrinho', 'Sobrinho'), ('sobrinha', 'Sobrinha'), ('primo', 'Primo'), ('prima', 'Prima'), ('cunhado', 'Cunhado'), ('cunhada', 'Cunhada'), ('genro', 'Genro'), ('nora', 'Nora'), ('neto', 'Neto'), ('neta', 'Neta')], default='responsável', max_length=40)),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moradores_parentes', to='moradores.Morador')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Nome do funcionário', max_length=100)),
                ('cpf', models.CharField(blank=True, help_text='CPF do Funcionário', max_length=150)),
                ('rg', models.CharField(blank=True, help_text='RG do Funcionário', max_length=150)),
                ('cargo', models.CharField(blank=True, help_text='Cargo do Funcionário', max_length=150)),
                ('Expediente', models.CharField(blank=True, help_text='Horário do Expediente do Funcionário', max_length=150)),
                ('img', models.ImageField(blank=True, help_text='Image do funcionaro do Morador', upload_to='Funcionario/Morador')),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morador_funcionario', to='moradores.Morador')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.CharField(help_text='Numero da do apartamento', max_length=40, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, help_text='O Nome do Animal', max_length=150)),
                ('tipo', models.CharField(choices=[('cães', 'Cães'), ('gatos', 'Gatos'), ('pássaros', 'Pássaros'), ('peixes', 'Peixes'), ('hamster', 'Hamster'), ('porquinho da ídia', 'Porquinho da Índia'), ('coelho', 'Coelho')], default='cães', help_text='O Tipo do Animal de Estimação', max_length=150)),
                ('raca', models.CharField(blank=True, help_text='A Raça do Animal de Estimação', max_length=150)),
                ('cor', models.CharField(blank=True, help_text='A Cor do Animal de Estimação', max_length=150)),
                ('img', models.ImageField(blank=True, help_text='Imagem do Animal de Estimação', upload_to='Animal/Morador')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_estimção', to='moradores.Morador')),
            ],
        ),
    ]
